
default: &default
  adapter: postgresql
  encoding: unicode
  database: api_blog
  username: alex
  password: qwer

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default


test:
  <<: *default


production:
  <<: *default

